						<?php
//
// File generated by ... on the 2018-09-23T22:46:51+0200
// Please do not edit manually
//

/**
 * Classes and menus for sample-add-class-router (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



class Router extends NetworkDevice
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'state_attcode' => '',
			'reconc_keys' => array('name', 'org_id', 'organization_name'),
			'db_table' => 'router',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'sample-add-class-router/images/router.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeIPAddress("ip_mgmt_addr", array("allowed_values"=>null, "sql"=>'ip_mgmt_addr', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDate("last_mtce_date", array("allowed_values"=>null, "sql"=>'last_mtce_date', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeIPAddress("network_address", array("allowed_values"=>null, "sql"=>'network_address', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("number_ports", array("allowed_values"=>null, "sql"=>'number_ports', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("number_ports_used", array("allowed_values"=>null, "sql"=>'number_ports_used', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("technology", array("allowed_values"=>new ValueSetEnum("tcpip,ethernet,ethernet,fddi,others"), "display_style"=>'radio_horizontal', "sql"=>'technology', "default_value"=>'', "is_null_allowed"=>true, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'contacts_list',
  1 => 'documents_list',
  2 => 'tickets_list',
  3 => 'providercontracts_list',
  4 => 'services_list',
  5 => 'applicationsolution_list',
  6 => 'physicalinterface_list',
  7 => 'connectablecis_list',
  'col:col1' => 
  array (
    'fieldset:Server:baseinfo' => 
    array (
      0 => 'name',
      1 => 'org_id',
      2 => 'status',
      3 => 'business_criticity',
      4 => 'location_id',
      5 => 'rack_id',
      6 => 'enclosure_id',
    ),
    'fieldset:Server:moreinfo' => 
    array (
      0 => 'brand_id',
      1 => 'model_id',
      2 => 'iosversion_id',
      3 => 'ip_mgmt_addr',
      4 => 'technology',
      5 => 'nb_u',
      6 => 'ram',
      7 => 'serialnumber',
      8 => 'asset_number',
      9 => 'network_address',
      10 => 'number_ports',
      11 => 'number_ports_used',
    ),
  ),
  'col:col2' => 
  array (
    'fieldset:Server:Date' => 
    array (
      0 => 'move2production',
      1 => 'purchase_date',
      2 => 'last_mtce_date',
      3 => 'end_of_warranty',
    ),
    'fieldset:Server:power' => 
    array (
      0 => 'powerA_id',
      1 => 'powerB_id',
      2 => 'redundancy',
    ),
    'fieldset:Server:otherinfo' => 
    array (
      0 => 'description',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'org_id',
  2 => 'status',
  3 => 'business_criticity',
  4 => 'location_id',
  5 => 'rack_id',
  6 => 'enclosure_id',
  7 => 'brand_id',
  8 => 'model_id',
  9 => 'iosversion_id',
  10 => 'technology',
  11 => 'serialnumber',
  12 => 'asset_number',
  13 => 'move2production',
  14 => 'purchase_date',
  15 => 'end_of_warranty',
  16 => 'ip_mgmt_addr',
  17 => 'powerA_id',
  18 => 'powerB_id',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'org_id',
  1 => 'status',
  2 => 'business_criticity',
  3 => 'location_id',
  4 => 'brand_id',
  5 => 'model_id',
  6 => 'iosversion_id',
  7 => 'technology',
  8 => 'serialnumber',
));

	}


}